### PR TITLE
Remove checkboxes (and a whole mess of other stuff to make this actually work)

### PR DESCRIPTION
**Pull request by jfhbrook**
The end goal was to remove a checkbox called "Click if you're Jane-Claire" and another one called "bigpic roundups", since we always pretend we're jane-claire and bigpic roundups don't appear to work.

Because this project hasn't been touched in 3 years, and because there were a number of differencs between what's deployed and what's on master, I had to do a bunch of other work:

* Add a .nvmrc file so we can switch to a node version for which deps will actually install
* Add run-scripts to package.json
* Remove broken sass step--edit css directly
* Remove dependence on chrome canary for testing (I certainly don't have it installed)
* Disable broken testing
* Document the current process, replacing the README left over from the boilerplate
* Change the jquery ajax call to be the same as what's in prod instead of hitting a defunct heroku box

I can't test this out locally properly because the kinja API appears to dynamically set CORS headers based on host, and as you might imagine localhost:3000 is a no-go. I suspect that when this was last touched that the app ran on heroku and hit the heroku shim API and that this was just never updated when someone decided to push to s3 instead.

I also need to detail how to do the deploy to s3, but I figure I'll do that after I actually get it up there.

### CODE REVIEW

**Comment by jfhbrook** [comment]
@ashtonG adding you mostly because I want to better understand why CORS headers look right in prod but not locally

In terms of deploy I'll make a local backup so it won't be a big deal

**Comment by jfhbrook** [comment]
I'm gonna try pushing this to prod and see what happens and will close if it does the right thing, otherwise restore and :man_shrugging:

**Comment by ashtonG** [comment]
the actual code for CORS handling is done here: https://github.com/gawkermedia/kinja-api/blob/master/src/main/scala/com/kinja/api/filters/CORSFilter.scala. Essentially, we only add the allowed methods and origins headers on a successful call, otherwise we fail generically.
the whitelist is handled here: https://github.com/gawkermedia/kinja-shared-config/blob/master/shared/cors-whitelist.conf

**Comment by jlaurito** [comment]
thanks @bregenspan

**Pull request merged**
